apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoexamplewebapp-dev0
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ujvaritamas/kubernetes_learning.git
    targetRevision: HEAD
    path: helm/examplewebapp
  destination:
    server: https://kubernetes.default.svc
    namespace: examplewebapp-dev0

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true #delete old components
